name: Prettier & ESLint

on:
  pull_request:
    branches: ['*']

jobs:
  eslint:
    name: Run prettier and eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Prettier
        run: |
          npm install prettier@2.8.8

      - name: Run Prettier
        run: npm run prettier:format
          --config ..prettierrc.js
        continue-on-error: false

      - name: Install ESLint
        run: |
          npm install eslint@8.40.0
          npm install eslint-config-universe@11.2
          npm install @typescript-eslint/parser"@5.59.2
          npm install @typescript-eslint/eslint-plugin@5.59.2

      - name: Run ESLint
        run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
        continue-on-error: false
